### ISSUE TITLE
Use Github flavoured markdown

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-docs#21]
Is this possible? If it is, configure it.

**Comment by subhankarb** [comment]
It can be done.
With https://github.com/Zopieux/py-gfm which is a python-markdown extension.
Using it with mkdocs we can generate GitHub-Flavored Markdown.

In mkdocs we can use any extension by adding it in `mkdocs.yml`

so we can add like this:
```yml
- py-gfm:
      repo_url_shortener: true
      base_repo_url: 'https://github.com/Zopieux/py-gfm'
```
